import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    nav_home: "Home",
    nav_work: "Work",
    nav_resume: "Resume",
    nav_say_hi: "Say hi",
    hero_eyebrow: "SOCIAL STRATEGY '26",
    hero_name: "Nikita Zhorov",
    hero_role_prefix: "An",
    hero_role_suffix: "based in Germany.",
    hero_desc: "Driving brand growth through viral content strategies and data-driven community management.",
    hero_cta_works: "See Works",
    hero_cta_reach: "Reach out...",
    works_eyebrow: "Case Studies",
    works_heading: "Featured",
    works_heading_italic: "campaigns",
    works_subtext: "A selection of social media strategies that delivered measurable results.",
    works_view_all: "View all work",
    journal_eyebrow: "Journal",
    journal_heading: "Social",
    journal_heading_italic: "insights",
    journal_subtext: "Deep dives into social trends, platform updates, and marketing psychology.",
    journal_view_all: "View all",
    stats_followers: "Followers Gained",
    stats_engagement: "Avg Engagement",
    stats_campaigns: "Viral Campaigns",
    footer_marquee: "GROWING BRANDS • ",
    footer_heading: "Let's grow",
    footer_heading_italic: "your presence.",
    footer_available: "Available for projects",
    contact_title: "Say",
    contact_title_italic: "Hi!",
    contact_subtitle: "Let's discuss your next big project.",
    contact_label_name: "Name",
    contact_label_email: "Email",
    contact_label_message: "Message",
    contact_placeholder_name: "Your name",
    contact_placeholder_message: "Tell me about your project...",
    contact_btn_send: "Send Message",
    case_study_title: "Social Media",
    case_study_title_italic: "Promotion",
    case_study_challenge_title: "The Challenge",
    case_study_challenge_desc: "A lifestyle brand struggling with low engagement and stagnant follower growth needed a complete social overhaul to reach a younger, more dynamic audience.",
    case_study_strategy_title: "The Strategy",
    case_study_strategy_desc: "We implemented a 'Viral-First' content strategy, focusing on high-energy short-form video and community-driven storytelling that resonated with Gen-Z trends.",
    case_study_results_title: "The Results",
    case_study_results_desc: "Within 6 months, engagement rates spiked by 300%, and the brand saw a 50k+ increase in organic followers, leading to a 40% boost in direct-to-consumer sales.",
    neo_ai_title: "NEO-AI",
    neo_ai_subtitle: "AI Education School",
    neo_ai_challenge_title: "The Challenge",
    neo_ai_challenge_desc: "NEO-AI needed a distinctive visual identity that reflects the cutting-edge nature of artificial intelligence while remaining accessible and inspiring for students.",
    neo_ai_strategy_title: "Visual Strategy",
    neo_ai_strategy_desc: "We developed a clean, high-tech aesthetic using 3D renders, vibrant blue accents, and surreal AI-generated imagery to create a 'future-ready' brand feel.",
    neo_ai_results_title: "The Result",
    neo_ai_results_desc: "A cohesive Instagram grid that increased organic reach by 450% and established NEO-AI as a premium leader in the AI education space.",
    neo_case_hero_eyebrow: "NEO AI SCHOOL: SMM & Design Ecosystem Case Study",
    neo_case_hero_title: "Unlock Your Future with AI",
    neo_case_overview_title: "Project Overview",
    neo_case_overview_body: "NEO AI SCHOOL is an innovative EdTech platform dedicated to bridging the gap between complex Artificial Intelligence technologies and practical career application. The school targets professionals, entrepreneurs, and creatives looking to integrate AI into their workflows to stay competitive. In a crowded market of 'AI gurus,' NEO AI SCHOOL positions itself as a premium, structured, and results-oriented academy. The project’s core value lies in transforming 'hype' into 'hard skills,' shifting the narrative from AI as a threat to AI as a strategic partner.",
    neo_case_objectives_title: "Objectives",
    neo_case_objectives_body: "The primary goal was to design a digital presence that reflects the school's cutting-edge nature while maintaining educational authority. Specific objectives included:",
    neo_case_obj_1_title: "Trust & Authority",
    neo_case_obj_1_desc: "Establishing a professional 'tech-forward' image to distance the brand from low-quality AI courses.",
    neo_case_obj_2_title: "Information Architecture",
    neo_case_obj_2_desc: "Creating a visual system capable of explaining complex technical concepts through simple, digestible formats.",
    neo_case_obj_3_title: "Conversion-Driven Design",
    neo_case_obj_3_desc: "Developing a 'FOMO' (Fear Of Missing Out) and urgency-based framework to drive course enrollments.",
    neo_case_obj_4_title: "Community Building",
    neo_case_obj_4_desc: "Creating a sense of belonging to an elite group of 'future-thinkers.'",
    neo_case_strategy_title: "Visual & Content Strategy",
    neo_case_strategy_body: "The strategy is built on Neo-Modernism and Digital Minimalism. We avoided the cliché 'matrix-style' or 'green-code' AI tropes in favor of a clean, high-contrast aesthetic.",
    neo_case_strat_1_title: "Color Palette",
    neo_case_strat_1_desc: "A dominant Electric Blue (#0055FF) represents technology and trust, paired with a monochrome (Black/White/Grey) base for readability and professional rigor.",
    neo_case_strat_2_title: "Typography",
    neo_case_strat_2_desc: "We utilized bold, geometric sans-serif typefaces to ensure maximum impact and clarity across mobile screens.",
    neo_case_strat_3_title: "Imagery Logic",
    neo_case_strat_3_desc: "We combined surreal 3D renders (symbolizing the abstract nature of AI) with high-contrast B&W photography (humanizing the technology).",
    neo_case_strat_4_title: "The 'Dot' Element",
    neo_case_strat_4_desc: "The signature blue dot from the logo is used as a consistent anchor across all layouts, reinforcing brand recall in every scroll.",
    neo_case_breakdown_title: "Content Examples Breakdown",
    neo_case_post1_title: "Visionary/Educational (Post 1): 'Unlock Your Future with AI'",
    neo_case_post1_task: "Broad reach and mission statement.",
    neo_case_post1_exec: "Minimalist 3D brain visualization. It visualizes 'neural networks' in a tangible, friendly way, lowering the barrier to entry for beginners.",
    neo_case_post2_title: "Strategic/B2B (Post 2): 'Strategic AI Adoption'",
    neo_case_post2_task: "Positioning AI as a business tool, not a toy.",
    neo_case_post2_exec: "Chess-themed 3D composition. This metaphorical approach appeals to decision-makers, emphasizing 'outmaneuvering competitors' and 'predicting shifts.'",
    neo_case_post3_title: "Community & Conversion (Post 3): 'Where are you?'",
    neo_case_post3_task: "Engagement and driving immediate action.",
    neo_case_post3_exec: "Post 3 uses a 'magazine cover' style to target identity ('Are you a future-thinker?').",
    neo_case_post4_title: "Community & Conversion (Post 4): 'Tick Tock'",
    neo_case_post4_task: "Engagement and driving immediate action.",
    neo_case_post4_exec: "Post 4 uses a surrealist melting clock (Salvador Dalí reference) to create a psychological sense of urgency without looking like a 'cheap sale' banner.",
    neo_case_design_title: "Design System",
    neo_case_design_body: "To ensure scalability and consistency, we developed a modular design system:",
    neo_case_ds_1_title: "Visual Anchor",
    neo_case_ds_1_desc: "Every post features the 'neo-AI' header for instant brand recognition.",
    neo_case_ds_2_title: "Grid System",
    neo_case_ds_2_desc: "A flexible layout that allows for both text-heavy educational carousels and high-impact single-image posters.",
    neo_case_ds_3_title: "Graphic Accents",
    neo_case_ds_3_desc: "Use of 'caution tape' textures and bold overlays to highlight calls to action (CTAs), ensuring they stand out even during fast scrolling.",
    neo_case_ds_4_title: "Scalability",
    neo_case_ds_4_desc: "The templates allow the school's internal team to generate new content (case studies, news, or tips) while maintaining the premium look.",
    neo_case_results_title: "Results",
    neo_case_results_body: "The implementation of this visual and content system led to:",
    neo_case_res_1_title: "Brand Cohesion",
    neo_case_res_1_desc: "A 100% unified look across all touchpoints, significantly increasing brand 'expensive feel.'",
    neo_case_res_2_title: "Higher Engagement",
    neo_case_res_2_desc: "Surrealist 3D visuals saw a 40% higher save rate compared to standard stock imagery.",
    neo_case_res_3_title: "Structured Perception",
    neo_case_res_3_desc: "The clear hierarchy of information reduced the 'cognitive load' for users, leading to higher click-through rates on educational content.",
    neo_case_res_4_title: "Strategic Positioning",
    neo_case_res_4_desc: "Successfully moved the brand from 'another AI course' to a 'premium AI academy' category.",
    neo_case_impact_title: "Impact",
    neo_case_impact_body: "This project demonstrates how design functions as a business strategy. By creating a sophisticated visual language, we successfully marketed a 'difficult' and 'scary' topic like AI as a structured, accessible, and essential career move. For NEO AI SCHOOL, this identity became the foundation for their market authority, allowing them to scale their ad spend with high-converting, professional assets.",
    neo_case_takeaways_title: "Key Takeaways",
    neo_case_takeaways_body: "",
    neo_case_kt_1_title: "Metaphor over Literalism",
    neo_case_kt_1_desc: "Using chess and melting clocks to explain strategy and urgency is more effective than generic 'robot' icons.",
    neo_case_kt_2_title: "High Contrast = High Authority",
    neo_case_kt_2_desc: "The blue-on-white/black scheme creates a 'tech-native' feel that commands attention.",
    neo_case_kt_3_title: "Hybrid Aesthetics",
    neo_case_kt_3_desc: "Mixing 3D graphics with human photography bridges the gap between cold technology and human aspiration.",
    neo_case_cta: "READY TO MAKE YOUR MOVE? CONTACT US.",
  },
  de: {
    nav_home: "Start",
    nav_work: "Arbeit",
    nav_resume: "Lebenslauf",
    nav_say_hi: "Hallo sagen",
    hero_eyebrow: "SOZIALSTRATEGIE '26",
    hero_name: "Nikita Zhorov",
    hero_role_prefix: "Ein",
    hero_role_suffix: "mit Sitz in Deutschland.",
    hero_desc: "Markenwachstum durch virale Content-Strategien und datengesteuertes Community-Management vorantreiben.",
    hero_cta_works: "Arbeiten sehen",
    hero_cta_reach: "Kontaktieren...",
    works_eyebrow: "Fallstudien",
    works_heading: "Ausgewählte",
    works_heading_italic: "Kampagnen",
    works_subtext: "Eine Auswahl an Social-Media-Strategien, die messbare Ergebnisse geliefert haben.",
    works_view_all: "Alle Arbeiten",
    journal_eyebrow: "Journal",
    journal_heading: "Soziale",
    journal_heading_italic: "Einblicke",
    journal_subtext: "Tiefe Einblicke in soziale Trends, Plattform-Updates und Marketing-Psychologie.",
    journal_view_all: "Alle ansehen",
    stats_followers: "Gewonnene Follower",
    stats_engagement: "Durchschn. Engagement",
    stats_campaigns: "Virale Kampagnen",
    footer_marquee: "MARKEN WACHSEN LASSEN • ",
    footer_heading: "Lassen Sie uns",
    footer_heading_italic: "Ihre Präsenz ausbauen.",
    footer_available: "Verfügbar für Projekte",
    contact_title: "Sagen Sie",
    contact_title_italic: "Hallo!",
    contact_subtitle: "Lassen Sie uns über Ihr nächstes großes Projekt sprechen.",
    contact_label_name: "Name",
    contact_label_email: "Email",
    contact_label_message: "Nachricht",
    contact_placeholder_name: "Ihr Name",
    contact_placeholder_message: "Erzählen Sie mir von Ihrem Projekt...",
    contact_btn_send: "Nachricht senden",
    case_study_title: "Social Media",
    case_study_title_italic: "Promotion",
    case_study_challenge_title: "Die Herausforderung",
    case_study_challenge_desc: "Eine Lifestyle-Marke, die mit geringem Engagement und stagnierendem Follower-Wachstum zu kämpfen hatte, benötigte eine komplette soziale Überholung, um ein jüngeres, dynamischeres Publikum zu erreichen.",
    case_study_strategy_title: "Die Strategie",
    case_study_strategy_desc: "Wir haben eine 'Viral-First'-Content-Strategie implementiert, die sich auf hochenergetische Kurzvideos und community-gesteuertes Storytelling konzentriert, das mit Gen-Z-Trends resoniert.",
    case_study_results_title: "Die Ergebnisse",
    case_study_results_desc: "Innerhalb von 6 Monaten stiegen die Engagement-Raten um 300%, und die Marke verzeichnete einen Anstieg der organischen Follower um über 50.000, was zu einem Anstieg der Direktverkäufe um 40% führte.",
    neo_ai_title: "NEO-AI",
    neo_ai_subtitle: "KI-Bildungsschule",
    neo_ai_challenge_title: "Die Herausforderung",
    neo_ai_challenge_desc: "NEO-AI benötigte eine unverwechselbare visuelle Identität, die den innovativen Charakter der künstlichen Intelligenz widerspiegelt und gleichzeitig für Studenten zugänglich und inspirierend bleibt.",
    neo_ai_strategy_title: "Visuelle Strategie",
    neo_ai_strategy_desc: "Wir haben eine saubere High-Tech-Ästhetik mit 3D-Renderings, leuchtend blauen Akzenten und surrealen KI-generierten Bildern entwickelt, um ein 'zukunftssicheres' Markengefühl zu schaffen.",
    neo_ai_results_title: "Das Ergebnis",
    neo_ai_results_desc: "Ein kohärentes Instagram-Grid, das die organische Reichweite um 450% steigerte und NEO-AI als Premium-Marktführer im Bereich KI-Bildung etablierte.",
    neo_case_hero_eyebrow: "NEO AI SCHOOL: SMM & Design Ökosystem Fallstudie",
    neo_case_hero_title: "Entsperren Sie Ihre Zukunft mit KI",
    neo_case_overview_title: "Projektübersicht",
    neo_case_overview_body: "NEO AI SCHOOL ist eine innovative EdTech-Plattform, die sich der Überbrückung der Lücke zwischen komplexen Technologien der Künstlichen Intelligenz und der praktischen Karriereanwendung widmet. Die Schule richtet sich an Fachleute, Unternehmer und Kreative, die KI in ihre Arbeitsabläufe integrieren möchten, um wettbewerbsfähig zu bleiben. In einem überfüllten Markt von 'KI-Gurus' positioniert sich die NEO AI SCHOOL als erstklassige, strukturierte und ergebnisorientierte Akademie. Der Kernwert des Projekts liegt in der Umwandlung von 'Hype' in 'Hard Skills' und der Verschiebung des Narrativs von KI als Bedrohung hin zu KI als strategischem Partner.",
    neo_case_objectives_title: "Ziele",
    neo_case_objectives_body: "Das Hauptziel bestand darin, eine digitale Präsenz zu entwerfen, die den innovativen Charakter der Schule widerspiegelt und gleichzeitig die pädagogische Autorität wahrt. Zu den spezifischen Zielen gehörten:",
    neo_case_obj_1_title: "Vertrauen & Autorität",
    neo_case_obj_1_desc: "Etablierung eines professionellen, 'technologieorientierten' Images, um die Marke von minderwertigen KI-Kursen abzuheben.",
    neo_case_obj_2_title: "Informationsarchitektur",
    neo_case_obj_2_desc: "Schaffung eines visuellen Systems, das in der Lage ist, komplexe technische Konzepte durch einfache, leicht verständliche Formate zu erklären.",
    neo_case_obj_3_title: "Konversionsorientiertes Design",
    neo_case_obj_3_desc: "Entwicklung eines auf 'FOMO' (Fear Of Missing Out) und Dringlichkeit basierenden Rahmens, um die Kursanmeldungen voranzutreiben.",
    neo_case_obj_4_title: "Gemeinschaftsbildung",
    neo_case_obj_4_desc: "Schaffung eines Gefühls der Zugehörigkeit zu einer Elitegruppe von 'Zukunftsdenkern'.",
    neo_case_strategy_title: "Visuelle & Content-Strategie",
    neo_case_strategy_body: "Die Strategie basiert auf Neomoderne und digitalem Minimalismus. Wir haben die klischeehaften 'Matrix-Style'- oder 'Green-Code'-KI-Tropen zugunsten einer sauberen, kontrastreichen Ästhetik vermieden.",
    neo_case_strat_1_title: "Farbpalette",
    neo_case_strat_1_desc: "Ein dominantes Electric Blue (#0055FF) repräsentiert Technologie und Vertrauen, gepaart mit einer monochromen Basis (Schwarz/Weiß/Grau) für Lesbarkeit und professionelle Strenge.",
    neo_case_strat_2_title: "Typografie",
    neo_case_strat_2_desc: "Wir haben fettgedruckte, geometrische serifenlose Schriftarten verwendet, um maximale Wirkung und Klarheit auf mobilen Bildschirmen zu gewährleisten.",
    neo_case_strat_3_title: "Bildlogik",
    neo_case_strat_3_desc: "Wir kombinierten surreale 3D-Renderings (die die abstrakte Natur der KI symbolisieren) mit kontrastreicher Schwarz-Weiß-Fotografie (die die Technologie humanisiert).",
    neo_case_strat_4_title: "Das 'Punkt'-Element",
    neo_case_strat_4_desc: "Der charakteristische blaue Punkt aus dem Logo wird als konsistenter Anker in allen Layouts verwendet und verstärkt die Markenwiedererkennung bei jedem Scrollen.",
    neo_case_breakdown_title: "Aufschlüsselung der Inhaltsbeispiele",
    neo_case_post1_title: "Visionär/Pädagogisch (Post 1): 'Entsperren Sie Ihre Zukunft mit KI'",
    neo_case_post1_task: "Breite Reichweite und Leitbild.",
    neo_case_post1_exec: "Minimalistische 3D-Gehirn-Visualisierung. Sie visualisiert 'neuronale Netze' auf greifbare, freundliche Weise und senkt die Eintrittsbarriere für Anfänger.",
    neo_case_post2_title: "Strategisch/B2B (Post 2): 'Strategische KI-Adoption'",
    neo_case_post2_task: "Positionierung von KI als Geschäftswerkzeug, nicht als Spielzeug.",
    neo_case_post2_exec: "Schach-Themen 3D-Komposition. Dieser metaphorische Ansatz spricht Entscheidungsträger an und betont das 'Ausmanövrieren von Wettbewerbern' und das 'Vorhersagen von Verschiebungen'.",
    neo_case_post3_title: "Gemeinschaft & Konversion (Post 3): 'Wo bist du?'",
    neo_case_post3_task: "Engagement und Förderung sofortigen Handelns.",
    neo_case_post3_exec: "Post 3 verwendet einen 'Magazin-Cover'-Stil, um die Identität anzusprechen ('Bist du ein Zukunftsdenker?').",
    neo_case_post4_title: "Gemeinschaft & Konversion (Post 4): 'Tick Tock'",
    neo_case_post4_task: "Engagement und Förderung sofortigen Handelns.",
    neo_case_post4_exec: "Post 4 verwendet eine surrealistische schmelzende Uhr (Salvador-Dalí-Referenz), um ein psychologisches Gefühl der Dringlichkeit zu erzeugen, ohne wie ein 'billiges Verkaufsbanner' auszusehen.",
    neo_case_design_title: "Designsystem",
    neo_case_design_body: "Um Skalierbarkeit und Konsistenz zu gewährleisten, haben wir ein modulares Designsystem entwickelt:",
    neo_case_ds_1_title: "Visueller Anker",
    neo_case_ds_1_desc: "Jeder Post enthält den 'neo-AI'-Header für sofortige Markenwiedererkennung.",
    neo_case_ds_2_title: "Rastersystem",
    neo_case_ds_2_desc: "Ein flexibles Layout, das sowohl textlastige Bildungskaruselle als auch wirkungsvolle Einzelbild-Poster ermöglicht.",
    neo_case_ds_3_title: "Grafische Akzente",
    neo_case_ds_3_desc: "Verwendung von 'Absperrband'-Texturen und fettgedruckten Overlays, um Handlungsaufforderungen (CTAs) hervorzuheben und sicherzustellen, dass sie auch beim schnellen Scrollen auffallen.",
    neo_case_ds_4_title: "Skalierbarkeit",
    neo_case_ds_4_desc: "Die Vorlagen ermöglichen es dem internen Team der Schule, neue Inhalte (Fallstudien, Nachrichten oder Tipps) zu generieren und dabei den Premium-Look beizubehalten.",
    neo_case_results_title: "Ergebnisse",
    neo_case_results_body: "Die Implementierung dieses Visuellen- und Content-Systems führte zu:",
    neo_case_res_1_title: "Markenkohäsion",
    neo_case_res_1_desc: "Ein zu 100% einheitlicher Look über alle Touchpoints hinweg, was das 'teure Gefühl' der Marke erheblich steigerte.",
    neo_case_res_2_title: "Höheres Engagement",
    neo_case_res_2_desc: "Surrealistische 3D-Visualisierungen verzeichneten eine um 40% höhere Speicherrate im Vergleich zu Standard-Stockbildern.",
    neo_case_res_3_title: "Strukturierte Wahrnehmung",
    neo_case_res_3_desc: "Die klare Informationshierarchie reduzierte die 'kognitive Belastung' für die Nutzer, was zu höheren Klickraten bei Bildungsinhalten führte.",
    neo_case_res_4_title: "Strategische Positionierung",
    neo_case_res_4_desc: "Erfolgreiche Verschiebung der Marke von der Kategorie 'ein weiterer KI-Kurs' hin zu einer 'Premium-KI-Akademie'.",
    neo_case_impact_title: "Auswirkung",
    neo_case_impact_body: "Dieses Projekt zeigt, wie Design als Geschäftsstrategie fungiert. Durch die Schaffung einer anspruchsvollen visuellen Sprache ist es uns gelungen, ein 'schwieriges' und 'beängstigendes' Thema wie KI als strukturierten, zugänglichen und wesentlichen Karriereschritt zu vermarkten. Für die NEO AI SCHOOL wurde diese Identität zur Grundlage für ihre Marktautorität und ermöglichte es ihnen, ihre Werbeausgaben mit hochkonvertierenden, professionellen Assets zu skalieren.",
    neo_case_takeaways_title: "Wichtige Erkenntnisse",
    neo_case_takeaways_body: "",
    neo_case_kt_1_title: "Metapher über Literalismus",
    neo_case_kt_1_desc: "Die Verwendung von Schach und schmelzenden Uhren zur Erklärung von Strategie und Dringlichkeit ist effektiver als generische 'Roboter'-Icons.",
    neo_case_kt_2_title: "Hoher Kontrast = Hohe Autorität",
    neo_case_kt_2_desc: "Das Blau-auf-Weiß/Schwarz-Schema erzeugt ein 'technologie-natives' Gefühl, das Aufmerksamkeit erregt.",
    neo_case_kt_3_title: "Hybride Ästhetik",
    neo_case_kt_3_desc: "Die Mischung aus 3D-Grafiken und menschlicher Fotografie schließt die Lücke zwischen kalter Technologie und menschlichem Streben.",
    neo_case_cta: "BEREIT FÜR IHREN NÄCHSTEN SCHRITT? KONTAKTIEREN SIE UNS.",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
